# Generated by Django 4.1 on 2022-09-03 03:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('english_word', models.CharField(max_length=32, unique=True)),
                ('chinese_word', models.CharField(max_length=32)),
                ('example', models.CharField(blank=True, default='No Example', max_length=128)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'vocabulary',
            },
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['english_word'], name='english_word_idx'),
        ),
    ]
