# Generated by Django 4.1 on 2023-04-22 04:04

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('en_word', models.CharField(max_length=32, unique=True)),
                ('cn_word', models.CharField(max_length=32)),
                ('example', models.CharField(blank=True, default='No Example', max_length=256)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'vocabulary',
            },
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['en_word'], name='en_word_idx'),
        ),
    ]
